set nu
set autoindent
set nocompatible
set syntax=on
set showmode
set cindent
set showcmd
set mouse=a
set encoding=utf-8
set t_Co=256
set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=2
set cursorline
set textwidth=100
set wrap
set linebreak
set wrapmargin=2
set scrolloff=5
set sidescrolloff=15
set laststatus=2
set ruler
set showmatch
set hlsearch
set incsearch
set ignorecase
set smartcase
set spell spelllang=en_us
set nobackup
set undofile
set autochdir
set noerrorbells
set visualbell
set noerrorbells
set autoread
set wildmenu
set wildmode=longest:list,full
set listchars=tab:»■,trail:■
set list
