set tabstop=4
set cindent
set autoindent
set shiftwidth=4
set nobackup
set noswapfile
set undofile
set nu
set nocompatible
set syntax=on
set showmode
set showcmd
set encoding=utf-8
set t_Co=256
set cursorline
set textwidth=100
set wrap
set linebreak
set wrapmargin=2
set scrolloff=5
set sidescrolloff=15
set laststatus=2
set ruler
set showmatch
set hlsearch
set incsearch
set ignorecase
set smartcase
set undofile
set nobackup
set noundofile
set autochdir
set noerrorbells
set visualbell
set noerrorbells
set autoread
set wildmenu
set wildmode=longest:list,full
